name: braintree_payment
description: Braintree Payment plugin for Flutter apps by Deligence Technologies. This payment gateway plugin lets you integrate Braintree Drop In payment UI in just 4 easy steps.
version: 1.2.4
author: Deligence <flutter@deligence.com>
homepage: https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.deligence.braintree_payment
    pluginClass: BraintreePaymentPlugin
